import type { Metadata } from "next";
import "./globals.css";
import { Box, Container, CssBaseline, InitColorSchemeScript, ThemeProvider } from "@mui/material";
import MyAppBar from "@/components/appbar";
import theme from "@/theme";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body>
        <InitColorSchemeScript attribute="class" />
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <MyAppBar />
            <Container maxWidth="lg">
              <Box
                sx={{
                  my: 4,
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'center',
                  alignItems: 'center',
                }}
              >
                {children}
              </Box>
            </Container>
          </ThemeProvider>
      </body>
    </html>
  );
}
