import type { Metadata } from "next";
import "./globals.css";
import { Box } from "@mui/material";
import MyAppBar from "@/components/appbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Box>
          <MyAppBar />
          {children}
        </Box>
      </body>
    </html>
  );
}
